### ISSUE TITLE
Calendar 7/17 - 7/23

### ISSUE THREAD

**Issue by finnbear** [PythagorStudios/pythagorstatic#11]
# Pythagor Studios Calendar
-Every Sunday, jobs will be assigned to each member.  
-Every subsequent Saturday, progress will be assessed.  
-On Saturday, if a member has fully completed their assigned work as well as something extra, they will be awarded a small amount of equity (1-3%).  If a member has not completed half or more of their work, they will lose 1% equity.
-Every member must at least record one priority each week, while having more than one is encouraged. Equity cannot be earned by exceeding low expectations.
-Each member should email team@pythagorstudios.com with a list of their priorities should they be unable to communicate them otherwise.  
-Sanjit may choose to dictate the priorities of each member, however should he fail to do so, they may dictate their own priorities.  

### Finn
- [ ] Edit crowdfunding video (provided Sanjit completes assets by Thursday morning as in #5)
- [x] Start work on APEX game (provided preliminary graphics are provided)
- [x] Improve and document game engine  
(+1) Start work on Saturn Spaceport as a side project to facilitate learning  
(+1) Write calendar

### Teo
- [x] Draw assets for apex demo game (See #10) 
- [x] Get more familiar with GitHub (https://www.youtube.com/watch?v=0fKg7e37bQE)
paigns
- [ ] Digitize assets for apex demo game (See #10)

### Sanjit
- [ ] Finalize crowdfunding campaign
- [ ] Procure assets for crowdfunding
- [ ] Complete administrative tasks

### Jinho  
- [x] Write game engine blog post (provided Finn completes documentation)
- [x] Contribute to game mechanics on Google Docs  
- [x] Continue learning JavaScript                                                                                                           
(+1) Bio for Robert

### Daniel
- [x] Learn more WebGL
- [ ] Familiarize with Finn's code, add comments if needed
- [x] Coding tasks

### Robert
- [x] Learn JS and WebGL
- [x] Familiarize with Finn's code, add comments as necessary
- [x] Coding tasks

### All
- [ ] Draft a scheme for wages
- [ ] Plan IRL meetups

**Comment by finnbear** [comment]
Robert should not be assigned until next week, as he did not have any work to do.

**Comment by gamester543** [comment]
I don't have any coding tasks though....

**Comment by finnbear** [comment]
I know. Therefore you automatically finished that.
