### ISSUE TITLE
Calendar 7/10 - 7/16

### ISSUE THREAD

**Issue by finnbear** [PythagorStudios/pythagorstatic#9]
# Pythagor Studios Calendar
-Every Sunday, jobs will be assigned to each member.  
-Every subsequent Saturday, progress will be assessed.  
-On Saturday, if a member has fully completed their assigned work as well as something extra, they will be awarded a small amount of equity (1-3%).  If a member has not completed half or more of their work, they will lose 1% equity.
-Every member must at least record one priority each week, while having more than one is encouraged. Equity cannot be earned by exceeding low expectations.
-Each member should email team@pythagorstudios.com with a list of their priorities should they be unable to communicate them otherwise.  
-Sanjit may choose to dictate the priorities of each member, however should he fail to do so, they may dictate their own priorities.  

### Finn
- [ ] Edit crowdfunding video (provided Sanjit completes assets by Thursday morning as in #5)
- [x] Learn WebGL
- [x] Finish game engine  
(+1) Download Maya, start learning it

### Teo
- [ ] Draw assets for APEX demo (See #10)
- [ ] Digitize them into either 2d graphics or 3d models (See #10)
- [x] Create or specify GitHub username to be added to the repository.
- [x] Learn the basics of GitHub <https://guides.github.com/activities/hello-world/>
- [x] Continue work on game mechanics

### Sanjit [AWAY]
- [ ] Finish making assets for crowdfunding video
- [x] Dictate a list of assets for Teo to produce (See #10, add to TBD list)
- [ ] Finalize crowdfunding campaign
- [ ] Update our social media with original content

### Jinho  
- [ ] Write APEX blog post and others (provided game engine is finished and documented)
- [x] Finalize bios and upload them
- [x] Continue work on game mechanics  
(+1) Begin learning JS

### Daniel  
- [x] Learn JS + WebGL (three.js)
- [x] Familiarize with Finn's code
- [x] Coding tasks

### All
- [ ] Draft a scheme for wages
- [x] Plan IRL meetups

**Comment by DanDan0101** [comment]
Fix your links.  The hashtag-1 is linking to issue #1

**Comment by Fluffmuffin369** [comment]
He knows

On Sat, Jul 9, 2016 at 5:21 PM, Daniel Sun <notifications@github.com> wrote:

> Fix your links. The hashtag-1 is linking to issue #1
> <https://github.com/PythagorStudios/pythagorstatic/issues/1>
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/PythagorStudios/pythagorstatic/issues/9#issuecomment-231563206>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATSw7USoIlyVhhiH_cXxH4TX2TB5SRckks5qUDsYgaJpZM4JIuvw>
> .
>



-- 
Sincerely,

*ME, *
*MYSELF, *
*AND I,*

aka شمس الدين الدين أبو عبد الله محمد بن عبد الله بن محمد بن إبراهيم بن
يوسف-اللواتي آل طنجي بن بطوطة بن حميد الغازي
(Shams Din al-Din Abu Abdallah Muhammad ibn Abdallah ibn Muhammad ibn
Ibrahim ibn Yusuf al-Lawati al-Tanji ibn Battuta ibn Hamid al-Ghazi), the
awesome Muslim explorer dude,

aka a Pastafarian
aka a Linnist (see the caliphs, Max Wu, me, Albert, or Victor for more
details)

Union General, John Sedgewick's Last Words:
*They couldn't hit an elephant at this distance. *

*Mexican Revolution General, Pancho Villa's **Last Words: *
*Don't let it end like this. Tell them I said something!*

**Comment by finnbear** [comment]
Yea I realized that. Tell me if you can think of another way.

**Comment by DanDan0101** [comment]
`test`

**Comment by DanDan0101** [comment]
Priority \#1

**Comment by DanDan0101** [comment]
- [x] ABLSD
- [x] asdf
- [ ] test

**Comment by DanDan0101** [comment]
@finnbear

**Comment by DanDan0101** [comment]
test:
/play trombone

**Comment by DanDan0101** [comment]
# 123

**Comment by finnbear** [comment]
Nice idea. I will try it.

**Comment by finnbear** [comment]
Guys, check off the things you complete during this coming week.

**Comment by Fluffmuffin369** [comment]
#1: Bios
#2: Starfish Blog Post
#3: APEX Mechanics Notes

On Sat, Jul 9, 2016 at 7:25 PM, Finn Bear <notifications@github.com> wrote:

> Guys, check off the things you complete during this coming week.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/PythagorStudios/pythagorstatic/issues/9#issuecomment-231566938>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATSw7ZEEuQK2fRl6J5lJxd-I0RoMA6Umks5qUFgKgaJpZM4JIuvw>
> .
>



-- 
Sincerely,

*ME, *
*MYSELF, *
*AND I,*

aka شمس الدين الدين أبو عبد الله محمد بن عبد الله بن محمد بن إبراهيم بن
يوسف-اللواتي آل طنجي بن بطوطة بن حميد الغازي
(Shams Din al-Din Abu Abdallah Muhammad ibn Abdallah ibn Muhammad ibn
Ibrahim ibn Yusuf al-Lawati al-Tanji ibn Battuta ibn Hamid al-Ghazi), the
awesome Muslim explorer dude,

aka a Pastafarian
aka a Linnist (see the caliphs, Max Wu, me, Albert, or Victor for more
details)

Union General, John Sedgewick's Last Words:
*They couldn't hit an elephant at this distance. *

*Mexican Revolution General, Pancho Villa's **Last Words: *
*Don't let it end like this. Tell them I said something!*

**Comment by Fluffmuffin369** [comment]
I can't do anything on the APEX blog post until the game engine is done.

**Comment by teodage** [comment]
squirrels MUST DIE

**Comment by DanDan0101** [comment]
@finnbear did @teodage agree to your terms and conditions of Github usage?

**Comment by Fluffmuffin369** [comment]
Teo says he did.

On Sun, Jul 10, 2016 at 4:45 PM, Daniel Sun <notifications@github.com>
wrote:

> @finnbear <https://github.com/finnbear> did @teodage
> <https://github.com/teodage> agree to your terms and conditions of Github
> usage?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/PythagorStudios/pythagorstatic/issues/9#issuecomment-231618107>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATSw7TAbZ8O0_FbAJk9ClBNZkmzgtX1eks5qUYQRgaJpZM4JIuvw>
> .
>



-- 
Sincerely,

*ME, *
*MYSELF, *
*AND I,*

aka شمس الدين الدين أبو عبد الله محمد بن عبد الله بن محمد بن إبراهيم بن
يوسف-اللواتي آل طنجي بن بطوطة بن حميد الغازي
(Shams Din al-Din Abu Abdallah Muhammad ibn Abdallah ibn Muhammad ibn
Ibrahim ibn Yusuf al-Lawati al-Tanji ibn Battuta ibn Hamid al-Ghazi), the
awesome Muslim explorer dude,

aka a Pastafarian
aka a Linnist (see the caliphs, Max Wu, me, Albert, or Victor for more
details)

Union General, John Sedgewick's Last Words:
*They couldn't hit an elephant at this distance. *

*Mexican Revolution General, Pancho Villa's **Last Words: *
*Don't let it end like this. Tell them I said something!*
